# Generated by Django 5.2.4 on 2025-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0002_alter_consultation_options_remove_consultation_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="patient_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Telefone do Paciente",
            ),
        ),
    ]
