# Generated by Django 5.2.4 on 2025-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctor_created_at_doctor_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
